x-json-logging: &json-logging
  driver: json-file
  options:
    max-size: "10m"
    max-file: "3"

services:
  mongodb:
    logging: *json-logging
  backend:
    logging: *json-logging
  frontend:
    logging: *json-logging
  frontend-debian:
    logging: *json-logging
  frontend-yarn:
    logging: *json-logging
  nginx:
    logging: *json-logging
